### ISSUE TITLE
why “num_fill = count * B * T - N” ?

### ISSUE THREAD

**Issue by LordHui** [akanazawa/human_dynamics#1]
https://github.com/akanazawa/human_dynamics/blob/67bc2be22f2fc125883bcbe98afb54dca3d47b49/src/evaluation/tester.py#L280-L295

Is it the proper way to add margins for every batch?
suppose `N = len(all_images) == 101`, `B=1`, `T=20`,thus `count==13`
then  `num_fill==159` !!!

`T>>matgin`will get a reasonable 'num_fill', or add margin for each frame sequnence.
the way of adding margin in the code seems faster.

**Comment by jasonyzhang** [comment]
Fixed! `num_fill` should be a function of `g`, not `T`.
