### ISSUE TITLE
How to accelerate the prediction with hallucinator?

### ISSUE THREAD

**Issue by Zetee** [akanazawa/human_dynamics#10]
Hi! I used yolo to get bbox and ran inference on single image with hallucinator model, but the hmmr prediction takes over 600ms to produce the joints on my 1080 GPU computer. Is there any thing I can do to speed up this process. I would be very grateful if you can provide some clues about this work.

**Comment by jasonyzhang** [comment]
Are you batching your predictions? 600ms sounds about right for the forward pass, but you should be able perform the hallucinations for ~8 images at once.

**Comment by Zetee** [comment]
Thanks for your reply! I intend to perform a real time detection, so only one image is sent to the hallucinator every time. The batching strategy works well on videos.

**Comment by jasonyzhang** [comment]
Try removing everything from the fetch_dict that you don't need. That may buy you a little bit more speed.
