### ISSUE TITLE
SMPL to tf.records script

### ISSUE THREAD

**Issue by mkocabas** [akanazawa/human_dynamics#11]
Hi @akanazawa and @jasonyzhang,

Thanks for the training release!

I assume `src.datasets.smpl_to_tfrecords.py` is not uploaded to github. Could you provide that file?

Best!

**Comment by jasonyzhang** [comment]
Thanks for catching that. `smpl_to_tfrecords.py` has been uploaded.

**Comment by mkocabas** [comment]
Great, thanks!
