### ISSUE TITLE
NBA dataset unavailable

### ISSUE THREAD

**Issue by ptx9363** [akanazawa/human_dynamics#15]
I have seen "Unless otherwise indicated, all models are trained with Human3.6M, Penn Action, and NBA." In your paper, but i can't find any clues about NBA dataset in this repos. Can you give any cues for it and i wish to reproduce your experiments correctly.

**Comment by akanazawa** [comment]
Hi, 

Yes, we're going through some license related issues for this dataset, but we're working hard to getting it released!

Thanks,

Angjoo

**Comment by pengying1625** [comment]
Hi，
Great works, thanks. And I'm also trying to reporduce your experimts, wondering when will the NBA dataset be released？
Thanks

**Comment by hongsukchoi** [comment]
@akanazawa 
Thanks for your great work. Is the license issues solved? I would love to reproduce your work and use in my research

**Comment by guofeisun** [comment]
@akanazawa
Interesting work. By the way, any progress about the NBA dataset?

**Comment by akanazawa** [comment]
Hi,

We have an unfortunate update, we initially thought we could releasing this data, but there has been a merger between the company that originally curated the data and now we don't have the proper rights to licensing this dataset :( We're not happy about this either but there's not much we can do. Hope you understand. 

Best,

Angjoo
