### ISSUE TITLE
Could you please post my fork link in your README?

### ISSUE THREAD

**Issue by Zju-George** [akanazawa/human_dynamics#16]
I've forked your hmmr project and successfully run it on Windows and I've made small changes (eg. write predicts.pose into json) and reuse them in Unity. Could you please post my fork link to ur Readme? (https://github.com/Zju-George/human_dynamics) Because I believe that people really want the result to be used in their own applications and I really want to contribute!

If you couldn't do that, I understand and that's okay, just mention. Thank you guys you have done an **amazing** job! @jasonyzhang @pannaf @akanazawa

**Comment by akanazawa** [comment]
Definitely!! Thanks a lot for the contribution and keep it going!! Adding it now!

Best,

Angjoo

**Comment by UserNameIsAlredyTaken** [comment]
@Zju-George, could you please write windows specific instalation guide?
It would help a lot!

**Comment by UserNameIsAlredyTaken** [comment]
@Zju-George, I was able to start your human_dinamics fork on windows!
But I still don't understand how to use your unity addon and it looks like animation support was not added to the repo.
Could you please leave some instructions on your fork's page and add animation support.
It would be useful for everyone interested in your work.
