### ISSUE TITLE
resluts are wrong

### ISSUE THREAD

**Issue by xywu10** [akanazawa/human_dynamics#19]
the paramers predicted are totally wrong,  
![图片](https://user-images.githubusercontent.com/54127852/63069267-ddb9c280-bf48-11e9-91a7-abfefcbc421c.png),
what's the problem of this? can you tell me?

**Comment by akanazawa** [comment]
Hi,

This seems very weird. I'm not sure what happened to the input image either. It seems like others were able to run our demo.. so I'm not sure what is happening here. Please make sure that all the package versions match exactly whats in the README and the requirements.txt. 

Best,

Angjoo

**Comment by xywu10** [comment]
Hi,
Thanks. When the sequence length is equal to 13, the answer seems to be right. So only one frame is valid at a time.

**Comment by XezXey** [comment]
I've face the same problem and try to reduce the sequence length equal to 13 and it doesn't work but when i try to decrease the mini-batch size from 8 to 1. It work well. What is this size of mini-batch stand for? A input image for prediction?

**Comment by 511963041** [comment]
The same problem.  Win10
change sequence length or mini-batch size doesn't work for me

I finally solved this by changing torch to version 0.4.0 cuda90 , (error occur on torch 1.3.1 cu92) . So the code is good, cuda/torch version maight be the reason.
