### ISSUE TITLE
how to disable nmr_renderer or run without visualization?

### ISSUE THREAD

**Issue by ayjabia** [akanazawa/human_dynamics#2]
Hi,

Is there a way to run this code without the nmr_renderer library or a way to deactivate visualization?

Thanks,

**Comment by jasonyzhang** [comment]
If you only want to keep the predictions (3d joints, vertices, keypoints, etc), then you can comment out the part of the code that does the rendering: https://github.com/akanazawa/human_dynamics/blob/bf4d577e9cbbda3ae536dd8bf035cbfa7ab5261b/demo_video.py#L181-L191
