### ISSUE TITLE
human3.6 mosh_data

### ISSUE THREAD

**Issue by junhaozhang98** [akanazawa/human_dynamics#20]
Could you please provided the mosh_data including pose and shape parameters separately? It is critical to reproduce the best performance mentioned in your paper. Thanks.

**Comment by akanazawa** [comment]
Unfortunately, I would like to but I cannot due to legal reasons that are beyond my control. Please obtain permission from the authors of Human3.6M who have the rights. Thanks.

**Comment by Z-Z-J** [comment]
@junhaozhang98  你知道如何得到H3.6m泥参数现在？如果你知道，请告诉我。谢谢！！！
