### ISSUE TITLE
Could you provide any guides about how to get the mosh data for human 3.6m or other datasets?

### ISSUE THREAD

**Issue by xy-guo** [akanazawa/human_dynamics#21]
Do we need the 3D ground truth to get the mosh parameters (to project 3D mesh into 3D joints)? Could you provide some simple steps about how to get the mosh parameters?

**Comment by akanazawa** [comment]
Please refer to the authors of Mosh, or check out this new dataset and paper: 

https://amass.is.tue.mpg.de/en

which should address your concern. 

Best,

A

**Comment by Z-Z-J** [comment]
@xy - guo Do you know how to get the H3.6m mosh parameters now ? If you know, please tell me . Thanks!!!
