### ISSUE TITLE
about run it web cam

### ISSUE THREAD

**Issue by wm901115nwpu** [akanazawa/human_dynamics#24]
Can I run the model in the web cam, If it works, how to do it?

**Comment by jasonyzhang** [comment]
The model can be run on any video with a person. If you can extract a sequence of image frames from the webcam, you should be able to run the model. [HMR](https://github.com/akanazawa/hmr) has a webcam demo, so you can start by modifying that code. The model should work best on videos with a framerate of 25-30 fps.
