### ISSUE TITLE
fine-tune the model, cannot load mocap_neutrMosh

### ISSUE THREAD

**Issue by ikvision** [akanazawa/human_dynamics#27]
My goal is to finetune the model published on my 2d pose dataset.

As a starting point I trying to create the simplest training script without Human3.6:
When running . 
`python -m src.main --pretrained_model_path ./models/hmr_noS5.ckpt-642561 --data_dir ./human_dynamics/tf_dataset --batch_size=8 --datasets penn_action --log_dir logs_release --num_conv_layers 3 --T 20 --mocap_datasets CMU,jointLim --use_3d_label`

I created mocap_dataset for CMU,jointLim  in /tf_dataset/mocap_neutrMosh/neutrSMPL_ and was able to load the created tf_records manually.

I get the following error:
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Feature: shape (data type: float) is required but could not be found.
> 	 [[Node: input_smpl_loader/read_smpl_data/ParseSingleExample/ParseSingleExample = ParseSingleExample[Tdense=[DT_FLOAT, DT_FLOAT], dense_keys=["pose", "shape"], dense_shapes=[[72], [10]], num_sparse=0, sparse_keys=[], sparse_types=[], _device="/job:localhost/replica:0/task:0/device:CPU:0"](input_smpl_loader/read_smpl_data/ReaderReadV2:1, input_smpl_loader/read_smpl_data/ParseSingleExample/Const, input_smpl_loader/read_smpl_data/ParseSingleExample/Const)]]

**Comment by jasonyzhang** [comment]
Seems like the shape is missing from the example. Make sure you're creating the examples in the tfrecord using something like:
https://github.com/akanazawa/human_dynamics/blob/e266fadd79668eccc9b078c4ccd4284491972812/src/datasets/smpl_to_tfrecords.py#L70-L74

**Comment by ikvision** [comment]
Wow, thank you for the quick reply, indeed I was creating temporal example that does only have pose.
If I understand the default training uses the non temporal representation, wouldn't it be better to set temporal to False in the smpl tf_record:
https://github.com/akanazawa/human_dynamics/blob/master/src/datasets/smpl_to_tfrecords.py#L24
Is there a script dedicated for FineTunning in the repos?

**Comment by jasonyzhang** [comment]
You actually need to also produce tfrecords with temporal=False (--notemporal). The temporal tfrecords were used to train a discriminator on delta pose, which is no longer used in the public model. The non-temporal tfrecords are used to train a discriminator on pose and shape.

If you are trying to finetune the model, you should probably use your data to train the encoder. Making the tfrecords for your dataset should looks something like https://github.com/akanazawa/human_dynamics/blob/master/src/datasets/upenn_to_tfrecords_video.py

**Comment by fanhaidi** [comment]
@ikvision Could you guide me how to create mocap_dataset for CMU,jointLim in /tf_dataset/mocap_neutrMosh/neutrSMPL_ ?
