### ISSUE TITLE
Bounding Box Processing penn_action

### ISSUE THREAD

**Issue by ikvision** [akanazawa/human_dynamics#29]
When using visualize_tf_records on penn_action dataset it is seems that the pre-processing jitters around the person bounding box, introducing large variability in time that doesn't exist in the original video. 
In the example below, from Frame 0 to Frame 3 there was no major change in the person location or its joints, still the pre-process image is considerably different.
Do you think smoothing the human bounding box over time would be beneficial, or is it an advantage to generate this jittering?

penn_action/train/penn_action_00_copy00_hmr_noS5.ckpt-642561.tfrecord
Frame 0:
![image](https://user-images.githubusercontent.com/11877852/65539037-7f73ee00-debd-11e9-9deb-0834ba561469.png)
Frame 1: 
![image](https://user-images.githubusercontent.com/11877852/65539067-8dc20a00-debd-11e9-94b2-ca29b676ed43.png)
Frame 3:
![image](https://user-images.githubusercontent.com/11877852/65539092-961a4500-debd-11e9-8dc4-7f3d8b2f28fb.png)

**Comment by jasonyzhang** [comment]
You are correct that the current data augmentation regime is applied to each frame independently. This is how the submission model and public models are trained.

We also tried applying the augmentation independently per tube such that all image in the same tube receive the same augmentation. We found the performance difference to be insignificant.
