### ISSUE TITLE
Can't install pytorch==0.4.0

### ISSUE THREAD

**Issue by tcboy88** [akanazawa/human_dynamics#3]
Can't install pytorch==0.4.0, the oldest that I can find from https://pytorch.org/get-started/previous-versions/ is 0.4.1

Collecting torch==0.4.0 (from -r requirements.txt (line 1))
  ERROR: Could not find a version that satisfies the requirement torch==0.4.0 (from -r requirements.txt (line 1)) (from versions: 0.1.2, 0.1.2.post1)
ERROR: No matching distribution found for torch==0.4.0 (from -r requirements.txt (line 1))

**Comment by jasonyzhang** [comment]
What OS and CUDA version?

**Comment by lrquad** [comment]
You can run with pytorch==0.4.1. I tested it. But you need change all AT_ASSERT to AT_CHECK to install neural renderer
