### ISSUE TITLE
why do you pad the image use zeros ?

### ISSUE THREAD

**Issue by chingswy** [akanazawa/human_dynamics#30]
I noticed that the code use zeros images in edge:
https://github.com/akanazawa/human_dynamics/blob/6328a3c3a274c241219d9baab72169cc47ae089a/src/evaluation/tester.py#L286
Did you try use edge images instead of zeros ?

**Comment by jasonyzhang** [comment]
The model was trained with zero padding. It is possible that edge padding would do better, but we've tried experiments where the model is both trained and tested with edge padding and the difference was not significant.

**Comment by jasonyzhang** [comment]
Nonetheless, you are welcome to try edge padding and let us know if it works better!
