### ISSUE TITLE
no metadata.xml

### ISSUE THREAD

**Issue by LH-Abner** [akanazawa/human_dynamics#31]
I run the read_human36m.py ,but there is no the metadata.xml . I have the camera.mat human36m_big.mat  part_cmap.mat  skel.mat, but I do not how to produce the metadata.xml, maybe i miss some things?

**Comment by akanazawa** [comment]
That comes with the original dataset when you download it from their website. It might also be in this repo: https://github.com/anibali/h36m-fetch/blob/master/metadata.xml I'm not sure if that's correct but follow the original author's instructions: http://vision.imar.ro/human3.6m/description.php

Best,

a
