### ISSUE TITLE
get the past and future pose from one single image?

### ISSUE THREAD

**Issue by seamanj** [akanazawa/human_dynamics#36]
Is it possible that given a video of only one frame, can we get the past and future pose just from that frame?

**Comment by jasonyzhang** [comment]
You can make a video with one frame and directly run the model. You can also try repeating the same image 13 times (the fov of the model) here https://github.com/akanazawa/human_dynamics/blob/6328a3c3a274c241219d9baab72169cc47ae089a/demo_video.py#L147-L153

**Comment by seamanj** [comment]
Hi, Jason

Thanks for your reply.
I already tried the first method, which gives me an error like:

```
100%|██████████| 1/1 [00:00<00:00, 24.96it/s]
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "PoseFlow/tracker-general.py", line 212, in <module>
    num_persons = max(num_persons, track[frame_name][pid]['new_pid'])
KeyError: 'new_pid'
Start pose tracking...

Issue running PoseFlow. Please make sure you can run the above command from the commandline.

Process finished with exit code 1
```

I will let the second method and let you know what the result will be. 

Appreciated!
