### ISSUE TITLE
how long it will take to convert the datasets into TFRecords

### ISSUE THREAD

**Issue by seamanj** [akanazawa/human_dynamics#39]
Dear author

I was trying to train the model, however, it has to convert the datasets into TFRecords first. Out of time estimation, I was wondering how long it will take to convert each dataset into TFRecords, for example, for Penn Action Dataset and Human3.6M. And how long it will take to train the model from them? 

Thanks in advance

**Comment by akanazawa** [comment]
Hi,

To convert Penn Action it does not take that long, I think H36M takes a bit more bc we do this pre-augmentation thing.. maybe a day or so? 

Best,

Angjoo
