### ISSUE TITLE
a question about smpl_tfrecords.py

### ISSUE THREAD

**Issue by seamanj** [akanazawa/human_dynamics#41]
Dear author

when I tried to convert smpl to tfrecord for adversarial prior training, there is a flag named "temporal", whose default value is true. Its corresponding output directory is mocap_neutrMosh_temporal. However, when we do training, data_loader_sequence.py load data from mocap_neutrMosh folder. So my question is do we really need mocap_neutrMosh_temporal for training? what does it use for? Many thanks.

**Comment by jasonyzhang** [comment]
We used to train a discriminator for the change in pose, so mocap_neutrMosh was for delta poses. We no longer use that discriminator, so you can ignore that directory.
