### ISSUE TITLE
problem in downloading the pre-trained model

### ISSUE THREAD

**Issue by bala1144** [akanazawa/human_dynamics#47]
Hi,

I am unable to download the pre-trained model from the link provided in repo.

> --2020-01-27 18:04:16--  http://angjookanazawa.com/cachedir/hmmr/hmmr_models.tar.gz
Resolving angjookanazawa.com (angjookanazawa.com)... failed: Name or service not known.
wget: unable to resolve host address ‘angjookanazawa.com’

it would be great, if you can provide a solution to get the pre-trained models.

Thank you.

**Comment by guxiao0822** [comment]
Yes, can you please activate the url? @akanazawa 
Many Thanks

**Comment by jasonyzhang** [comment]
Hi,

Thank you for pointing out this issue! The link has been fixed.

Best,
Jason
