### ISSUE TITLE
neural render function called failed

### ISSUE THREAD

**Issue by yeetan** [akanazawa/human_dynamics#49]
File "G:\firestrike2020\human_dynamics-master\src\util\render\nmr_renderer.py", line 58, in __init__
    img_size, camera_mode='look_at', perspective=False)
TypeError: __init__() got an unexpected keyword argument 'camera_mode'

in file nmr_render.py, it failed to call nr.Renderer(),   feeds three parameters
       self.renderer = nr.Renderer(
            img_size, camera_mode='look_at', perspective=False)

but the nr.Renderer's definition as follow:
class Renderer(object):
    def __init__(self):

it accepts no parameter, it's a wired error

**Comment by jasonyzhang** [comment]
Hello,

Please make sure you are using the Pytorch version of NMR. The directions for installation are in the README https://github.com/akanazawa/human_dynamics#install-external-dependencies

Here's what the `__init__` should look like:
https://github.com/daniilidis-group/neural_renderer/blob/55a05a28d70e278edd9e04b812b27e747486ccaf/neural_renderer/renderer.py#L11-L19

Best,
Jason
