### ISSUE TITLE
3D information output

### ISSUE THREAD

**Issue by JoeyChuuichi** [akanazawa/human_dynamics#5]
Hello. I found the project is very amazing and want to implement it in my project.

I have now successfully run the code but I do not know where we can get the 3D information (Maybe (x-y-z)coordinate data?).

Could you help give more explanation on it?

**Comment by jasonyzhang** [comment]
The demo currently saves the predictions into a pickle here:
https://github.com/akanazawa/human_dynamics/blob/bf4d577e9cbbda3ae536dd8bf035cbfa7ab5261b/demo_video.py#L172-L176

The predictions are a dictionary which contains the 3D skeleton `'joints'` (Nx25x3) and the 3D vertices of the mesh `'verts'` (Nx6890x3).

**Comment by JoeyChuuichi** [comment]
> The demo currently saves the predictions into a pickle here:
> https://github.com/akanazawa/human_dynamics/blob/bf4d577e9cbbda3ae536dd8bf035cbfa7ab5261b/demo_video.py#L172-L176
> 
> The predictions are a dictionary which contains the 3D skeleton `'joints'` (Nx25x3) and the 3D vertices of the mesh `'verts'` (Nx6890x3).

@jasonyzhang 
Thank you so much!

**Comment by JoeyChuuichi** [comment]
@jasonyzhang 
I want to visualize the 3D skeleton result according to the 'joints' data. But I cannot find what each coordinate refers to. It seems that there are 23 joints, rather than 25, in the paper. I am confused about it.

**Comment by jasonyzhang** [comment]
There should be 25 keypoints in the 3D skeleton. Maybe you're looking at poses? SMPL uses the root joint and the rotation matrices of 23 joints to compute the mesh. Just to make sure, 'joints' should have dimension Nx25x3 and 'poses' should have dimension Nx24x3x3.

The 25 joints should correspond to the following:
```python
joint_names = [
        'R Heel', 'R Knee', 'R Hip', 'L Hip', 'L Knee', 'L Heel', 'R Wrist',
        'R Elbow', 'R Shoulder', 'L Shoulder', 'L Elbow', 'L Wrist', 'Neck',
        'Head', 'Nose', 'L Eye', 'R Eye', 'L Ear', 'R Ear', 'L Big Toe',
        'R Big Toe', 'L Small Toe', 'R Small Toe', 'L Ankle', 'R Ankle',
]
```

**Comment by Zju-George** [comment]
> Hello. I found the project is very amazing and want to implement it in my project.
> 
> I have now successfully run the code but I do not know where we can get the 3D information (Maybe (x-y-z)coordinate data?).
> 
> Could you help give more explanation on it?

The SMPL uses RHS, which is right-handed-system, so if you use it in your applications using LHS, you have to mordify the Quaternion accordingly.
Here's my fork link, I have transfered the result to Unity!
https://github.com/Zju-George/human_dynamics

**Comment by Zju-George** [comment]
> There should be 25 keypoints in the 3D skeleton. Maybe you're looking at poses? SMPL uses the root joint and the rotation matrices of 23 joints to compute the mesh. Just to make sure, 'joints' should have dimension Nx25x3 and 'poses' should have dimension Nx24x3x3.
> 
> The 25 joints should correspond to the following:
> 
> ```python
> joint_names = [
>         'R Heel', 'R Knee', 'R Hip', 'L Hip', 'L Knee', 'L Heel', 'R Wrist',
>         'R Elbow', 'R Shoulder', 'L Shoulder', 'L Elbow', 'L Wrist', 'Neck',
>         'Head', 'Nose', 'L Eye', 'R Eye', 'L Ear', 'R Ear', 'L Big Toe',
>         'R Big Toe', 'L Small Toe', 'R Small Toe', 'L Ankle', 'R Ankle',
> ]
> ```

How do I get root position....

**Comment by jasonyzhang** [comment]
We treat the pelvis as the mean of L Hip and R Hip
