### ISSUE TITLE
Can smpl convert to bvh? 

### ISSUE THREAD

**Issue by yeetan** [akanazawa/human_dynamics#50]
the output is a smpl's pkl file,  can it convert to a BVH file?

**Comment by jasonyzhang** [comment]
This seems like a better question for the SMPL or SMPL-X authors. But I did find [this project](https://github.com/Dene33/video_to_bvh) that converts the output of HMR to bvh. You should be able to swap out the HMR predictions for HMMR for more accurate pose estimations from video.

Best,
Jason
