### ISSUE TITLE
Model fails on demo video

### ISSUE THREAD

**Issue by tfederico** [akanazawa/human_dynamics#51]
Hi,

I installed the model following the description. I am using the indicated version of neural renderer.

However, when I try to test the model on the demo videos, only the first few frames are correct. In the remaining frames, the model produce a random output, such as:
https://drive.google.com/open?id=1v9FzSCawfBX_S_3LPtFAG3ZyjvBARAYG

Any suggestions about how to fix this? I checked the intermediate results and both AlphaPose and Poseflow produce the correct output.

**Comment by jasonyzhang** [comment]
This doesn't seem to be a problem with NMR since the extracted 2D skeleton looks off as well. I would start by double-checking your Tensorflow and CUDA versions. There's been a significant number of breaking changes in the new versions of Tensorflow.

**Comment by tfederico** [comment]
I am using Tensorflow 1.15 and CUDA 10. Unfortunately, I cannot downgrade
to previous versions of cuda.

Do you know which are these significant differences? So that I can try to
adapt the code to newer versions of tensorflow.

**Comment by jasonyzhang** [comment]
It appears that a lot of default options have changed, and some APIs have had breaking changes between 1.8.0 and 1.15.0. You can see the changelogs per version here: https://github.com/tensorflow/tensorflow/releases/tag/v1.15.0
