### ISSUE TITLE
I got a pickle result file for the example video, but I don't get the actual meaning of every key. 

### ISSUE THREAD

**Issue by hellozjj** [akanazawa/human_dynamics#52]
I got a pickle result file for the example video, but I don't get the actual meaning of every key. 
for example, what does the "joints" in the result mean? The shape of  "joints" is (frame_num, joint_num, 3), and is the position of every joint in every frame?

**Comment by jasonyzhang** [comment]
`joints` refers to the 3D joint locations of the 25 keypoints that we defined on the kinematic skeleton. There should be one prediction for each frame passed to the model. Joint order is described in #5

**Comment by hellozjj** [comment]
> `joints` refers to the 3D joint locations of the 25 keypoints that we defined on the kinematic skeleton. There should be one prediction for each frame passed to the model. Joint order is described in #5

Thank you very much?  And the pose means?  For every joint, pose is a 3x3 matrix， is the translate matrix?

**Comment by jasonyzhang** [comment]
poses is a rotation matrix corresponding to the SMPL joint

**Comment by hellozjj** [comment]
> poses is a rotation matrix corresponding to the SMPL joint

Thanks  very much!!

**Comment by hellozjj** [comment]
> `joints` refers to the 3D joint locations of the 25 keypoints that we defined on the kinematic skeleton. There should be one prediction for each frame passed to the model. Joint order is described in #5

Sorry to bother you with another question.
Is it that the 3D joint locations of the 25 keypoints in `Joints` is the relative coordinates to the root joint? 
If so, how can I get the world root location to visiualize the result?

**Comment by hellozjj** [comment]
> `joints` refers to the 3D joint locations of the 25 keypoints that we defined on the kinematic skeleton. There should be one prediction for each frame passed to the model. Joint order is described in #5

Is the `joints` refers to the 3D global or local locations? if is the global loacation, what's the coordinate origin ?
