### ISSUE TITLE
Issues running demo

### ISSUE THREAD

**Issue by natdring** [akanazawa/human_dynamics#53]
Hi,

I have followed the demo instructions from the README, but I can't seem to run the demo without encountering this error.

![image](https://user-images.githubusercontent.com/33533980/78214142-52565880-7469-11ea-821d-633d752d53e6.png)

I have all requirements installed and running the correct versions of CUDA and Python

Any suggestions about how to fix this?

**Comment by jasonyzhang** [comment]
That looks like a problem with Neural Mesh Renderer. You might have better luck opening an issue in their repo. But I would start by rebuilding from source (as opposed to pip install neural_renderer_pytorch). Also make sure the wheel that you're using to install pytorch is compatible with your CUDA version. The error actually looks like the wheel for pytorch was built for CUDA 10, so it's missing the header.

Best,
Jason

**Comment by natdring** [comment]
Thanks for the quick response Jason! I'll give it a try when I get the chance. 

Also, could you explain what you mean by "missing the header"? 
Sorry if that is a silly question, but I am quite new to all this.

Cheers,
Nat

**Comment by jasonyzhang** [comment]
What version of Pytorch are you using? You might need to install using something like
`pip install torch==1.2.0+cu90 torchvision==0.4.0+cu90 -f https://download.pytorch.org/whl/torch_stable.html` to get the wheel built for CUDA 9.0.

**Comment by natdring** [comment]
I have torch 0.4.0 from the requirements.txt

Here is a screenshot of my pip freeze

![image](https://user-images.githubusercontent.com/33533980/78324415-83965d80-7529-11ea-9f01-c9963fefc81e.png)

**Comment by natdring** [comment]
Also, I couldn't find a torch version 1.2.0+cu90. 

Instead I found only these ones:
![image](https://user-images.githubusercontent.com/33533980/78324554-e12aaa00-7529-11ea-91f3-e05f800ec601.png)

**Comment by jasonyzhang** [comment]
Try installing the wheel specifically for CUDA 9 here: https://pytorch.cn/previous-versions or see if any of the suggestions here help: https://github.com/rusty1s/pytorch_geometric/issues/114.

Otherwise, you could just install a newer version of Pytorch (>1.0) and there's like 2 lines of code you need to change #17

**Comment by natdring** [comment]
Is it possible to run the demo with CUDA 10? 

Or is CUDA 9.0 the only version that works correctly?

**Comment by jasonyzhang** [comment]
The code was written for and tested with the listed dependencies in the README
