### ISSUE TITLE
No progress with model.predict_all_image() when running demo on single video

### ISSUE THREAD

**Issue by natdring** [akanazawa/human_dynamics#55]
When running the demo on a single video with the command (from README):

```python -m demo_video --vid_path demo_data/penn_action-2278.mp4 --load_path models/hmmr_model.ckpt-1119816``` 

the process seems to halt and the progress remains at 0%.

Any ideas on what is going wrong?

![image](https://user-images.githubusercontent.com/33533980/78742844-e749cd80-7911-11ea-9449-acd0eca451c6.png)

**Comment by jasonyzhang** [comment]
If you have anything else running on the same GPU, you may be running out of memory. Difficult to debug without seeing which operations are taking up most of the time

**Comment by natdring** [comment]
That sounds like what is most likely happening. 

How could I go about solving this?

Is there somewhere in the code I can edit to lower memory consumption?

**Comment by jasonyzhang** [comment]
You can lower batch size (--batch_size 1) or reduce sequence length (--sequence_length 15). You can use nvidia-smi to check how much gpu memory you're using

**Comment by natdring** [comment]
Increasing the memory in my system solved this. 

Thanks for the suggestions!
