### ISSUE TITLE
How to extract camera position and rotation relative to model?

### ISSUE THREAD

**Issue by UserNameIsAlredyTaken** [akanazawa/human_dynamics#57]
My goal is to set camera in my unity scene so it would see the model like camera sees the person in video.
I was able to extract camera values for each frame.
In the article was said that it is _weak-perspective camera Π = [s, tx, ty]_, but I'm konfused how to use those values to set my camera position and rotation in scene.

**Comment by jasonyzhang** [comment]
In the weak perspective camera model, scale = focal_length / Z_avg.
Thus, you can approximate the location of the person in the 3D scene by translating the vertices by [tx, ty, f/s]. In practice, I've found that f=1 works reasonably well.

Best,
Jason

**Comment by nnop** [comment]
Sorry for commenting a closed issue.
But I want to ask what's the units of `tx`, `ty`? Is it pixel or meter?

Looking forward for your reply. 
@jasonyzhang
