### ISSUE TITLE
Convert predictions to world coordinates

### ISSUE THREAD

**Issue by tfederico** [akanazawa/human_dynamics#59]
Hi,

thanks for sharing the code, amazing work!

How can I convert the predictions of the model (joints & rotations) into world coordinates?

**Comment by jasonyzhang** [comment]
Hi,

You can approximate the 3D location of the person in world coordinates by translating the joints or vertices by [tx, ty, f/s]. See #57.

Best,
Jason

**Comment by tfederico** [comment]
What are t, s and f? Where can I find them?

**Comment by jasonyzhang** [comment]
The predicted camera contains [s, tx, ty] where s=scale, tx and ty are x and y translation. f=focal length, which is probably unknown but start with f=1.

**Comment by tfederico** [comment]
Amazing, thank you very much! Does the camera contain this parameters for all the joints?

Also, how can I use this parameters to translate the root rotation in world coordinates?

**Comment by jasonyzhang** [comment]
One weak-perspective camera is predicted per pose, so add the same translation to all vertices and joints. I'm not sure what it means to translate a root rotation. The root vertex should be translated with the same vector as all the other vertices.

**Comment by tfederico** [comment]
In DeepMimic they say that the root position and rotation are in world coordinates, while the other joints are in local coordinates. I thought that means that you are supposed to translate the root rotation as well

**Comment by nnop** [comment]
Why did `f=1` work well? 
Aren't the **weak-perspective** assumption make sense with large focal length (like 5000)? 
In that way the object is far away, so the camera perspective doesn't affect much.

**Comment by jasonyzhang** [comment]
The focal length is in normalized device coordinates, so a focal length of 1 corresponds to the 2 * max(H, W) in pixel units

**Comment by nnop** [comment]
`(H, W)` is the size of human bbox not the whole image, right?

**Comment by jasonyzhang** [comment]
Yes, I believe that is correct

**Comment by nnop** [comment]
<img width="498" alt="image" src="https://user-images.githubusercontent.com/23091984/199990021-2665d0d5-fdf5-48d8-931a-e1598f5bc6a6.png">

I did some math about the projection process, but not sure if it's correct.
Precisely speaking, it seems *focal length 1* in the NDC is corresponding to `max(H, W)/2` in the pixel frame. 
Could you help to confirm that?
