### ISSUE TITLE
Thread confusion，leading to bad results in the demo data

### ISSUE THREAD

**Issue by runningpp** [akanazawa/human_dynamics#62]
My envs：
ubuntu18.04 cuda10.0 cudnn7.6
tensorflow-gpu==1.13.1
pytorch=1.1 torchvision=0.3

I have ran the code included the Alphapose( provided pytorch verison) successfully.
when I ran the Alphapose projects in the given data, I could get the resonable 2d pose estimation. 
Howerver, when I ran the all code, so terrible results I got, 3D mesh  and even the 2D pose estimation were so bad, actually, only in the first few frames，it looked normal. 
I guess maybe the threads confused, but I didn‘t modify code.
I was confused why the code ran so bad in the given data, could you tell me how to fix it.

**Comment by jasonyzhang** [comment]
This is most likely the result of a version conflict. Please use the CUDA and TensorFlow versions described in the README
