### ISSUE TITLE
Did you test the hmmr model on the val set or the test set of 3DPW?

### ISSUE THREAD

**Issue by gsygsy96** [akanazawa/human_dynamics#63]
Hi @akanazawa @jasonyzhang, it seems that you assign the val split as the actual test set in prepare_dataset.sh. It's very puzzling.

**Comment by akanazawa** [comment]
Hi,

That's just a set of scripts, so in practice we make it for both test & val. It's set to default to val there because we always test on the val set first!

Best,

Angjoo

**Comment by gsygsy96** [comment]
Thanks! By the way, it seems that 'downtown_cafe_01' does not exist in the 3DPW dataset.
