### ISSUE TITLE
Is commercial license available for InstaVariety dataset?

### ISSUE THREAD

**Issue by foresee-ai** [akanazawa/human_dynamics#65]
Hi,  Is InstaVariety dataset for commercial use? If so, what is the contact info?

**Comment by jasonyzhang** [comment]
Hi,

The InstaVariety Dataset is only available for non-commercial academic use.

Best,
Jason

**Comment by foresee-ai** [comment]
Jason,

Thank you!  Still very much appreciated your work.

Heidi
