### ISSUE TITLE
problems with testing videos

### ISSUE THREAD

**Issue by XihuaQiao** [akanazawa/human_dynamics#68]
I find the first several frames in 'demo_output/penn_action-2278/hmmr_output/' folder is great. The 3D human model is excellent. However, in the rest frames in this folder, the model is strange. Here is the frame. I wonder if this is normal with the model or there is something wrong?
![image](https://user-images.githubusercontent.com/47941141/109611300-fdcfc780-7b68-11eb-9ce3-fc62833bdd58.png)

**Comment by jasonyzhang** [comment]
Hi,

What version of TensorFlow are you using?

This problem has popped up a couple of times due to using an unsupported version of TensorFlow. If you are not using the same set of dependency versions listed in the README, please try installing those first.

Best,
Jason

**Comment by XihuaQiao** [comment]
yeah, I try the same version. And now it works, thanks~
