### ISSUE TITLE
How to use hallucinator to predict with single image?

### ISSUE THREAD

**Issue by Zetee** [akanazawa/human_dynamics#7]
Hi! I'm really appreciated to see this brilliant work with code provided. The project successfully runs on my machine. I am wondering how to use hallucinator for prediction, since the demo script says only pred mode support now and I have found 'hal' in predefined mode. Looking forward to further update, thanks!

**Comment by Zetee** [comment]
It works when setting 'pred_mode' to 'hal', but with some jitters for videos.

**Comment by Zju-George** [comment]
> It works when setting 'pred_mode' to 'hal', but with some jitters for videos.

could you please tell me where to set the 'pred_mode', thx!

**Comment by Zetee** [comment]
> > It works when setting 'pred_mode' to 'hal', but with some jitters for videos.
> 
> could you please tell me where to set the 'pred_mode', thx!

just add flags in cmd, like "python -m demo_video --pred_mode hal". you might need to change some codes correspondingly.

**Comment by seamanj** [comment]
To be honest, I still don't know how to predict the past and future pose from the single image. I mean, is it possible that given a video of only one frame, can we get the past and future pose just from that frame?
