### ISSUE TITLE
about output parameters

### ISSUE THREAD

**Issue by XihuaQiao** [akanazawa/human_dynamics#71]
is there any chance I could get the rotation (global orientation) vectors and translation vectors of the model for each frame? And the rotation and translation variable of cameras?

**Comment by XihuaQiao** [comment]
Does the root orientation which refers to the mean of 'L Hip' and 'R Hip' joints represent global orientation?

**Comment by jasonyzhang** [comment]
Global rotation is the first rotation matrix in the "poses" key of the output dictionary.
We use a weak-perspective camera model (scale + translation), so you can approximate the global translation following #57, #59.
