### ISSUE TITLE
about the unit of 2D pose parameters

### ISSUE THREAD

**Issue by XihuaQiao** [akanazawa/human_dynamics#72]
Is the 2D pose parameters or 'kps' parameters(25 x 2) pixel-based? Or what is the unit of 2D pose parameters? Thanks a lot

**Comment by XihuaQiao** [comment]
Or more specifically, what is the connection between 'kps' parameters and pixel-based 2D keypoints positions?

**Comment by XihuaQiao** [comment]
anyone could answer my question? Thanks a lot

**Comment by jasonyzhang** [comment]
'kps' is 2D pixel coordinates corresponding to each keypoint.

**Comment by XihuaQiao** [comment]
sorry to bother you, but I am not sure I can understand this type of 2D pixel coordinate. Could you provide further explain? Thanks a lot!
![image](https://user-images.githubusercontent.com/47941141/116982571-87337f80-acfb-11eb-9ad0-020a4dd1c6fc.png)

**Comment by jasonyzhang** [comment]
Oh looks like the coordinates are actually in normalized [-1, 1] space. To transform them to pixel coordinates for a 224x224 crop, you can do `224 * 0.5 * (kps  + 1)`.

**Comment by XihuaQiao** [comment]
Thanks a lot~
