### ISSUE TITLE
why use 25 joints instead of 24 joints?

### ISSUE THREAD

**Issue by XihuaQiao** [akanazawa/human_dynamics#73]
why HMMR use 25 joints instead of 24 joints as the general SMPL model use?

**Comment by jasonyzhang** [comment]
The 24 joints that the SMPL model uses do not necessarily correspond to the same joints used in various 2D datasets. As a result, we train a linear regressor that maps from the 6890 vertices of the SMPL mesh to the superset of all 2d keypoints used by various datasets (H3.6M, LSP, COCO, OpenPose, etc).

You can find the full list of keypoints here:
https://github.com/akanazawa/human_dynamics/blob/0887f37464c9a079ad7d69c8358cecd0f43c4f2a/src/datasets/video_in_the_wild_to_tfrecords.py#L85-L111
