### ISSUE TITLE
Project 2d and 3d keypoints on image

### ISSUE THREAD

**Issue by tfederico** [akanazawa/human_dynamics#76]
Hello,

I tried to project the 2d (kps) and 3d (joints) keypoints on an image, but it appears that there is an offset between where the points are projected and where they should be.

What I did was taking the keypoints (which are in the range [-1, 1]), add 1 and multiply by 0. Then, I multiply X and Y by the image width and height.

Am I doing it correctly? Do I need to add a translation somehow?

**Comment by tfederico** [comment]
Here is an example, where the 2d kps are the yellow ones and the 3d are the black ones

![Figure_1](https://user-images.githubusercontent.com/15323014/133787617-3f929541-b283-4b2a-994a-923b75c6cae4.png)

**Comment by jasonyzhang** [comment]
Hi,

The 3D keypoints are in the local 3D SMPL coordinate system (units of meters).
The 2D keypoints are in normalized w.r.t the _cropped frame_ taken as input, not w.r.t the full image frame.

3D keypoints are converted to 2D keypoints (w.r.t the crop) using scaled orthographic projection: x = s(X + t)
https://github.com/akanazawa/human_dynamics/blob/0887f37464c9a079ad7d69c8358cecd0f43c4f2a/src/tf_smpl/projection.py#L16-L29

To convert the 2D keypoints w.r.t the crop into 2D keypoints w.r.t the original image (this seems to be what you want), you will need the scaling factor and offset of the cropped box. These camera parameters (param["start_pt"], param["scale"]) are available here:
https://github.com/akanazawa/human_dynamics/blob/0887f37464c9a079ad7d69c8358cecd0f43c4f2a/demo_video.py#L153

An example of how to "undo" the crop transformation for the camera parameters is shown here
https://github.com/akanazawa/human_dynamics/blob/0887f37464c9a079ad7d69c8358cecd0f43c4f2a/src/util/render/nmr_renderer.py#L466-L481

Using `new_cam`, you can project the 3D keypoints into the original image space.

Best,
Jason
