### ISSUE TITLE
3D-Joints order and their coordinate system? 

### ISSUE THREAD

**Issue by OptimusPrimeCao** [akanazawa/human_dynamics#8]
Hi, I want to render the 3D-joints. Could you tell me the T x 25 x 3 joints‘ order and coordinate system?

**Comment by akanazawa** [comment]
Hi,
The names are:
```
joint_names= [
    'R Heel',
    'R Knee',
    'R Hip',
    'L Hip',
    'L Knee',
    'L Heel',
    'R Wrist',
    'R Elbow',
    'R Shoulder',
    'L Shoulder',
    'L Elbow',
    'L Wrist',
    'Neck',
    'Head',
    'Nose',
    'L Eye',
    'R Eye',
    'L Ear',
    'R Ear',
    'L Big Toe',
    'R Big Toe',
    'L Small Toe',
    'R Small Toe',
    'L Ankle',
    'R Ankle',
]
```
It's the usual cartesian coordinate system, in the image coordinate frame, if that's what you're asking.

**Comment by Zju-George** [comment]
> Hi, I want to render the 3D-joints. Could you tell me the T x 25 x 3 joints‘ order and coordinate system?

The SMPL uses RHS, which is right-handed-system, so if you use it in your applications use LHS, you have to mordify the Quaternion accordingly.
Here's my fork link, I have transfer the result to Unity!
https://github.com/Zju-George/human_dynamics
