### ISSUE TITLE
Created meshgrid gets distorted very fast

### ISSUE THREAD

**Issue by ayjabia** [akanazawa/human_dynamics#9]
I have ran the demo as instructed. The estimated human mesh is accurate for the first 3-4 frames. But then it gets distorted for the rest of the frames and makes no sense or human shape.
I have tried to run the code on the given videos and other videos but I always get 3-4 of accurate frames and the rest of the frames are distorted.
What could be the reason for that? Is that supposed to happen?
Thanks,

**Comment by akanazawa** [comment]
Hm this sounds like there's some issue. you should be able to recover the exact same videos that are on the project website because they were created with the released demo code.

**Comment by ayjabia** [comment]
I have the same environment. The only difference is that I am using CUDA 10 and Tensorflow  1.13.1.
The code compiles and runs and I get results. The only difference is that the estimated mesh is correct for the first 3-4 mesh and for the rest of the frames, estimated mesh is random and doesn't make sense or shape.

**Comment by Zju-George** [comment]
@ayjabia @akanazawa 
I have the same issue as described by ayjabia
it is penn_action-2278 result of frame 10, you can see it aligns very well
![image](https://user-images.githubusercontent.com/33959089/61434939-e5963f00-a969-11e9-9ab5-f0cf700157d6.png)
but here is  result of frame 43, which her leg is not aligned properly..
![frame000043](https://user-images.githubusercontent.com/33959089/61435303-c21fc400-a96a-11e9-9b6e-4b2fc2720992.png)
and I don't know if it is pose track(poseflow) problem or hmmr problem cuz those dots of poseflow didn't align well either.. so may you plz help me?

ps: I see the demo video put on hmmr project page of penn_action and I can see that it seems as same as my result I get here, so is it normal?

**Comment by jasonyzhang** [comment]
The temporal encoder has a receptive field of 13, which means that for the first 6 frames and last 6 frames, it doesn't have full field of view. The predictions for those frames will be slightly worse. You can use the `--trim` flag to automatically exclude those frames.

**Comment by Zju-George** [comment]
@jasonyzhang Thx, that make perfect sense!
